{% set name = "gmpy2" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmpy2-{{ version }}.tar.gz
  sha256: da75140bca128ece795895477e53b43773e3748aa90ba6170eae7ca2c74b82d1
  patches:
    - win_setup.diff

build:
  number: 0
  skip: True        # [win and vc<14]
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - pip
    - setuptools
    - wheel
  run:
    - python
    - mpir          # [win]
    - mpc

test:
  imports:
    - gmpy2
  requires:
    - pip
  commands:
    - pip check
  downstreams:
  # Additional testing with a downstream package sympy
    - sympy

about:
  home: https://pypi.python.org/pypi/gmpy2
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x'
  dev_url: https://github.com/aleaxit/gmpy
  doc_url: https://gmpy2.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - isuruf
