{% set name = "gmpy2" %}
{% set version = "2.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmpy2-{{ version }}.tar.gz
  sha256: bc297f1fd8c377ae67a4f493fc0f926e5d1b157e5c342e30a4d84dc7b9f95d96
  patches:
    - win_setup.diff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - gmp 6.2.1     # [unix]
    - mpir 3.0.0    # [win]
    - mpfr 4.0.2
    - mpc 1.1.0
    - pip
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('mpir') }} # [win]
    # have run_exports
    - gmp # [unix]
    - mpc
    - mpfr

test:
  imports:
    - gmpy2
  requires:
    - pip
  commands:
    - pip check
  # downstreams:
  # # Additional testing with a downstream package sympy
  #   - sympy

about:
  home: https://pypi.org/pypi/gmpy2
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x'
  dev_url: https://github.com/aleaxit/gmpy
  doc_url: https://gmpy2.readthedocs.io

extra:
  recipe-maintainers:
    - isuruf
