travis:
  secure:
    BINSTAR_TOKEN: lopvFSxwtTpEWB03WGykVlga0eyMXMHbSfnBAJE02fvr2KH2H+1tntrr17O3WgaAnyQy9W4RrFpZRn5Q/nct2Kt4yvfIRXD9AQt6y/SV1pI0SdqFpiG9/exotZXv7ts+ucNM78D1T1enT+NuSQOahhKFZ59oZFAAWEMNxvGruHqMX/BMMdWPhXQUFGHM+bJPwYM+ZznvxEPh6n8/tcgVPb3FkNKg3VqXf6/lR+Fs9VWT6KxTbwKcaKefSJMUtGoY7FnHzqyHNv7wi7M4rzoKQaDASKZ5OSSFiZ5WZfmZfPZoCaPZUubYKiBPBOSZ3Hl5TrNmgIVCdcxqhwkzypqyKc2wgzBm1O5pg1miJ2nRxx3B4HYVAyRUwhdREb/F+Ecv5/FT3Iyo2BO5foXFpfkOTEVs3opqz6l5Irpe3skTpGBn0Tgh+qFWemj+MCbsr1Cs8/TZBiLLH8zFBjx27I3AYs3go57UeyZ9jpDx0EotZCpOqn3I6bpTOQylaFCP7SjF4gBNRMFSaoMwhyDZWG8EfFFYzAzfI7kOGRR+cxwR/MVqkuhEC+Z5vIDcQXmMRS2KG3UXEp+XxSmuZ6Wam+VLOrqlzzqvvHHBjDxYm0uUkL0wDvyJRF0UaAlOONnQkuP7WQCVCfo11ohPEHc2GA/alyo4gwY/NHidD66SjIUWM/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
